---
abstract: 'Format perl files using Perl::Tidy'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Padre::Plugin::PerlTidy
name: Padre-Plugin-PerlTidy
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Padre: 0.26
  Perl::Tidy: 0
  perl: 5.8.1
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-PerlTidy
version: 0.07
